export const GAME_SETTINGS = Object.freeze({
  MAX_NAME_LENGTH: 5,
  MIN_CARS_REQUIRED: 2,
  MIN_ROUNDS_REQUIRED: 1,
  MIN_RANDOM_NUMBER: 0,
  MAX_RANDOM_NUMBER: 9,
  INCREASE_POSISION: 1,
  FORWARD_POINT: 4,
  INITIAL_POSITION: 0,
});

export const SYMBOLS = Object.freeze({
  EMPTY: '',
  DASH: '-',
  SPACE: ' ',
  COMMA: ',',
  COMMA_WITH_BLANK: ', ',
  COLON_WITH_BLACK: ' : ',
});
